server:
  port: 8080

spring:
  application:
    name: billing-project
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SmartBilling
    username: root
    password: rootpassword
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  invoice-limit: ${INVOICE_LIMIT}