version: '3.8'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: SmartBilling
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3306:3306'